name: Publish to Pypi

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
